# Generated by Django 3.1 on 2022-07-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_utrl_context',
            new_name='current_utrl_context_db',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tax',
        ),
        migrations.AddField(
            model_name='user',
            name='current_utrl_form_db',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
