# Generated by Django 3.1 on 2022-08-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220726_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_utrl',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
