# Generated by Django 3.1 on 2022-09-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220818_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_language_code',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='entity',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='entities', through='myapp.EntitySizeAmount', to='myapp.Size'),
        ),
    ]
