# Generated by Django 3.1 on 2022-09-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20220914_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entities',
            field=models.ManyToManyField(blank=True, to='myapp.Entity'),
        ),
    ]
