# Generated by Django 3.1 on 2022-12-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20221004_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_language_code',
            field=models.CharField(default='en', max_length=16),
        ),
    ]
